version: '3'
services:

  app:
    build:
      context: docker/app
    container_name: transactionapp-app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
      - ./docker/app/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - net
    depends_on:
      - mysql
      - redis

  worker:
    build:
      context: docker/worker
    container_name: transactionapp-worker
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    networks:
      - net
    depends_on:
      - app

  scheduler:
    build:
      context: docker/scheduler
    container_name: transactionapp-scheduler
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    networks:
      - net
    depends_on:
      - worker

  nginx:
    image: nginx:alpine
    container_name: transactionapp-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - net

  mysql:
    image: mysql:5.7
    container_name: transactionapp-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'transaction_app'
      MYSQL_USERNAME: 'laravel_user'
      MYSQL_PASSWORD: 'laravel_pass'
      MYSQL_ROOT_PASSWORD: 'root_pass'
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/setup.sql
      - mysql:/var/lib/mysql/
    networks:
      - net

  redis:
    image: redis:alpine
    container_name: transactionapp-redis
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - net

volumes:
  mysql:
    driver: local
  redis:
    driver: local

networks:
  net:
    driver: bridge
