version: '3'
services:

  php:
    build:
      context: docker/php
    container_name: transactionapp-php
    restart: unless-stopped
    tty: true
    working_dir: /var/www/transactionApp
    volumes:
      - ./src:/var/www/transactionApp
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - net
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: transactionapp-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/transactionApp
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - net

  mysql:
    image: mysql:5.7
    container_name: transactionapp-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: 'transaction_app'
      MYSQL_USERNAME: 'laravel_user'
      MYSQL_PASSWORD: 'laravel_pass'
      MYSQL_ROOT_PASSWORD: 'root_pass'
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/setup.sql
      - mysql:/var/lib/mysql/
    networks:
      - net

volumes:
  mysql:
    driver: local

networks:
  net:
    driver: bridge
